source 'https://rubygems.org'

gem "jekyll"
gem "html-proofer"


group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
  gem 'jekyll-redirect-from'
  gem 'jekyll-admin'
  gem 'github-pages'
end
